export const HERO_TIMING = {
  SEQUENCE_INITIAL_DELAY: 800,
  SEQUENCE_STEP_1_DELAY: 1800,
  SEQUENCE_STEP_DEFAULT_DELAY: 1100,
  SCRAMBLE_START_DELAY: 500,
  SCRAMBLE_INTERVAL: 35,
  WIPE_TRANSITION_DELAY: 1200,
  MOBILE_INTERACTION_RESET: 1500,
};

export const HERO_SCRAMBLE_CHARS = '!<>-_\\/[]{}—=+*^?#_~';
